language: go

sudo: required

go:
  - 1.9.x
install:
  - echo "Please don't go get"

services:
  - docker

before_install:
    
script:
  - ./contrib/ci.sh
  - make

after_success:
  - if [ ! -s "$TRAVIS_TAG" ] ; then
    make docker-push
  fi
